version: "3.9"

services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'userpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql

  #postgres:
  #  image: postgres:9.6
  #  environment:
  #    POSTGRES_DB: 'hydra'
  #    POSTGRES_USER: 'hydra'
  #    POSTGRES_PASSWORD: 'secret'
  #  ports:
  #    - 5432:5432
  #  networks:
  #    - restapi


volumes:
  mysql-data:
